spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: 'true'
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    username: root
    url: jdbc:mysql://localhost:3306/bank_svc
  redis:
    host: 127.0.0.1
    port: 6379
logging:
  level:
    com:
      querydsl:
        sql: DEBUG

      netflix:
        dgs:
          graphql: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework: INFO

jwt:
  secret: '`vY5LAwh*(m#3j#!w}XqQRCQj'
  access-expires-in: 86400
  refresh-secret: '`wzK1Erq4-9dziO^cyk8yEZea'
  refresh-expires-in: 2592000